drop extension if exists "pg_net";


  create table "public"."article" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "subtitle" character varying not null,
    "body" text not null,
    "image" character varying not null,
    "video_url" character varying not null,
    "audio" character varying,
    "tags" text[] not null,
    "like_count" integer default 0,
    "share_count" integer default 0
      );


alter table "public"."article" enable row level security;


  create table "public"."article_likes" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "article_id" integer,
    "ip_hash" text not null,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."article_likes" enable row level security;


  create table "public"."rant_views" (
    "rant_id" integer not null,
    "views" bigint not null default 0
      );


alter table "public"."rant_views" enable row level security;


  create table "public"."view_logs" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "rant_id" integer,
    "ip_address" text not null,
    "viewed_at" timestamp with time zone default now()
      );


alter table "public"."view_logs" enable row level security;

CREATE UNIQUE INDEX "Article Table_pkey" ON public.article USING btree (id);

CREATE UNIQUE INDEX "Article Table_title_key" ON public.article USING btree (title);

CREATE UNIQUE INDEX article_image_url_key ON public.article USING btree (image);

CREATE UNIQUE INDEX article_likes_pkey ON public.article_likes USING btree (id);

CREATE UNIQUE INDEX article_subtitle_key ON public.article USING btree (subtitle);

CREATE UNIQUE INDEX article_video_url_key ON public.article USING btree (video_url);

CREATE INDEX idx_article_likes_article_id ON public.article_likes USING btree (article_id);

CREATE INDEX idx_article_likes_ip_hash ON public.article_likes USING btree (ip_hash);

CREATE INDEX idx_likes_article_ip ON public.article_likes USING btree (article_id, ip_hash);

CREATE UNIQUE INDEX rant_views_rant_id_key ON public.rant_views USING btree (rant_id);

CREATE UNIQUE INDEX unique_like ON public.article_likes USING btree (article_id, ip_hash);

CREATE UNIQUE INDEX view_logs_pkey ON public.view_logs USING btree (id);

CREATE UNIQUE INDEX view_logs_rant_id_ip_address_key ON public.view_logs USING btree (rant_id, ip_address);

alter table "public"."article" add constraint "Article Table_pkey" PRIMARY KEY using index "Article Table_pkey";

alter table "public"."article_likes" add constraint "article_likes_pkey" PRIMARY KEY using index "article_likes_pkey";

alter table "public"."view_logs" add constraint "view_logs_pkey" PRIMARY KEY using index "view_logs_pkey";

alter table "public"."article" add constraint "Article Table_title_key" UNIQUE using index "Article Table_title_key";

alter table "public"."article" add constraint "article_image_url_key" UNIQUE using index "article_image_url_key";

alter table "public"."article" add constraint "article_subtitle_key" UNIQUE using index "article_subtitle_key";

alter table "public"."article" add constraint "article_video_url_key" UNIQUE using index "article_video_url_key";

alter table "public"."article_likes" add constraint "article_likes_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.article(id) ON DELETE CASCADE not valid;

alter table "public"."article_likes" validate constraint "article_likes_article_id_fkey";

alter table "public"."article_likes" add constraint "unique_like" UNIQUE using index "unique_like";

alter table "public"."rant_views" add constraint "rant_views_rant_id_fkey" FOREIGN KEY (rant_id) REFERENCES public.article(id) ON DELETE CASCADE not valid;

alter table "public"."rant_views" validate constraint "rant_views_rant_id_fkey";

alter table "public"."rant_views" add constraint "rant_views_rant_id_key" UNIQUE using index "rant_views_rant_id_key";

alter table "public"."view_logs" add constraint "view_logs_rant_id_fkey" FOREIGN KEY (rant_id) REFERENCES public.article(id) not valid;

alter table "public"."view_logs" validate constraint "view_logs_rant_id_fkey";

alter table "public"."view_logs" add constraint "view_logs_rant_id_ip_address_key" UNIQUE using index "view_logs_rant_id_ip_address_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.decrement_like_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE article
     SET like_count = like_count - 1
   WHERE id = OLD.article_id;

  -- Optional safety: prevent negative likes (business rule)
  UPDATE article
     SET like_count = GREATEST(like_count, 0)
   WHERE id = OLD.article_id;

  RETURN OLD;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment(table_name text, column_name text, row_id integer, id_column text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  result INTEGER;
BEGIN
  EXECUTE format(
    'UPDATE %I SET %I = %I + 1 WHERE %I = %L RETURNING %I',
    table_name, column_name, column_name, id_column, row_id, column_name
  )
  INTO result;

  IF result IS NULL THEN
    EXECUTE format(
      'INSERT INTO %I (%I, %I) VALUES (%L, 1)',
      table_name, id_column, column_name, row_id
    );
    RETURN 1;
  END IF;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment(table_name text, column_name text, row_id numeric, id_column text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  result INTEGER;
BEGIN
  EXECUTE format(
    'UPDATE %I SET %I = %I + 1 WHERE %I = %L RETURNING %I',
    table_name, column_name, column_name, id_column, row_id, column_name
  )
  INTO result;

  IF result IS NULL THEN
    EXECUTE format(
      'INSERT INTO %I (%I, %I) VALUES (%L, 1)',
      table_name, id_column, column_name, row_id
    );
    RETURN 1;
  END IF;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment(table_name text, column_name text, row_id text, id_column text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  result INTEGER;
BEGIN
  EXECUTE format(
    'UPDATE %I SET %I = %I + 1 WHERE %I = %L RETURNING %I',
    table_name, column_name, column_name, id_column, row_id, column_name
  )
  INTO result;

  IF result IS NULL THEN
    EXECUTE format(
      'INSERT INTO %I (%I, %I) VALUES (%L, 1)',
      table_name, id_column, column_name, row_id
    );
    RETURN 1;
  END IF;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment(table_name text, column_name text, row_id uuid, id_column text)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  result INTEGER;
BEGIN
  EXECUTE format('UPDATE %I SET %I = %I + 1 WHERE %I = %L RETURNING %I', table_name, column_name, column_name, id_column, row_id, column_name)
  INTO STRICT result;
  RETURN result;
EXCEPTION WHEN NO_DATA_FOUND THEN
  EXECUTE format('INSERT INTO %I (%I, %I) VALUES (%L, 1)', table_name, id_column, column_name, row_id);
  RETURN 1;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_hug_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  update article
  set like_count = like_count + 1 
  where id = new.article_id;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_like_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE article
     SET like_count = like_count + 1
   WHERE id = NEW.article_id;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_rant_views(rant integer)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  new_views BIGINT;
BEGIN
  INSERT INTO rant_views (rant_id, views)
  VALUES (rant, 1)
  ON CONFLICT (rant_id)
  DO UPDATE SET views = rant_views.views + 1
  RETURNING views INTO new_views;

  RETURN new_views;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_share_count(rant_id integer)
 RETURNS bigint
 LANGUAGE sql
AS $function$
  UPDATE article
  SET share_count = share_count + 1
  WHERE id = rant_id
  RETURNING share_count;
$function$
;

grant delete on table "public"."article" to "anon";

grant insert on table "public"."article" to "anon";

grant references on table "public"."article" to "anon";

grant select on table "public"."article" to "anon";

grant trigger on table "public"."article" to "anon";

grant truncate on table "public"."article" to "anon";

grant update on table "public"."article" to "anon";

grant delete on table "public"."article" to "authenticated";

grant insert on table "public"."article" to "authenticated";

grant references on table "public"."article" to "authenticated";

grant select on table "public"."article" to "authenticated";

grant trigger on table "public"."article" to "authenticated";

grant truncate on table "public"."article" to "authenticated";

grant update on table "public"."article" to "authenticated";

grant delete on table "public"."article" to "service_role";

grant insert on table "public"."article" to "service_role";

grant references on table "public"."article" to "service_role";

grant select on table "public"."article" to "service_role";

grant trigger on table "public"."article" to "service_role";

grant truncate on table "public"."article" to "service_role";

grant update on table "public"."article" to "service_role";

grant delete on table "public"."article_likes" to "anon";

grant insert on table "public"."article_likes" to "anon";

grant references on table "public"."article_likes" to "anon";

grant select on table "public"."article_likes" to "anon";

grant trigger on table "public"."article_likes" to "anon";

grant truncate on table "public"."article_likes" to "anon";

grant update on table "public"."article_likes" to "anon";

grant delete on table "public"."article_likes" to "authenticated";

grant insert on table "public"."article_likes" to "authenticated";

grant references on table "public"."article_likes" to "authenticated";

grant select on table "public"."article_likes" to "authenticated";

grant trigger on table "public"."article_likes" to "authenticated";

grant truncate on table "public"."article_likes" to "authenticated";

grant update on table "public"."article_likes" to "authenticated";

grant delete on table "public"."article_likes" to "service_role";

grant insert on table "public"."article_likes" to "service_role";

grant references on table "public"."article_likes" to "service_role";

grant select on table "public"."article_likes" to "service_role";

grant trigger on table "public"."article_likes" to "service_role";

grant truncate on table "public"."article_likes" to "service_role";

grant update on table "public"."article_likes" to "service_role";

grant delete on table "public"."rant_views" to "anon";

grant insert on table "public"."rant_views" to "anon";

grant references on table "public"."rant_views" to "anon";

grant select on table "public"."rant_views" to "anon";

grant trigger on table "public"."rant_views" to "anon";

grant truncate on table "public"."rant_views" to "anon";

grant update on table "public"."rant_views" to "anon";

grant delete on table "public"."rant_views" to "authenticated";

grant insert on table "public"."rant_views" to "authenticated";

grant references on table "public"."rant_views" to "authenticated";

grant select on table "public"."rant_views" to "authenticated";

grant trigger on table "public"."rant_views" to "authenticated";

grant truncate on table "public"."rant_views" to "authenticated";

grant update on table "public"."rant_views" to "authenticated";

grant delete on table "public"."rant_views" to "service_role";

grant insert on table "public"."rant_views" to "service_role";

grant references on table "public"."rant_views" to "service_role";

grant select on table "public"."rant_views" to "service_role";

grant trigger on table "public"."rant_views" to "service_role";

grant truncate on table "public"."rant_views" to "service_role";

grant update on table "public"."rant_views" to "service_role";

grant delete on table "public"."view_logs" to "anon";

grant insert on table "public"."view_logs" to "anon";

grant references on table "public"."view_logs" to "anon";

grant select on table "public"."view_logs" to "anon";

grant trigger on table "public"."view_logs" to "anon";

grant truncate on table "public"."view_logs" to "anon";

grant update on table "public"."view_logs" to "anon";

grant delete on table "public"."view_logs" to "authenticated";

grant insert on table "public"."view_logs" to "authenticated";

grant references on table "public"."view_logs" to "authenticated";

grant select on table "public"."view_logs" to "authenticated";

grant trigger on table "public"."view_logs" to "authenticated";

grant truncate on table "public"."view_logs" to "authenticated";

grant update on table "public"."view_logs" to "authenticated";

grant delete on table "public"."view_logs" to "service_role";

grant insert on table "public"."view_logs" to "service_role";

grant references on table "public"."view_logs" to "service_role";

grant select on table "public"."view_logs" to "service_role";

grant trigger on table "public"."view_logs" to "service_role";

grant truncate on table "public"."view_logs" to "service_role";

grant update on table "public"."view_logs" to "service_role";


  create policy "Authenticated Insert for Articles"
  on "public"."article"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() IS NOT NULL));



  create policy "Authenticated Update for Articles"
  on "public"."article"
  as permissive
  for update
  to authenticated
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));



  create policy "Delete the article row"
  on "public"."article"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."article"
  as permissive
  for select
  to public
using (true);



  create policy "allow trigger updates"
  on "public"."article"
  as permissive
  for update
  to public
using (true);



  create policy "Public can count hugs"
  on "public"."article_likes"
  as permissive
  for select
  to public
using (true);



  create policy "Public can hug"
  on "public"."article_likes"
  as permissive
  for insert
  to public
with check (true);



  create policy "delete"
  on "public"."article_likes"
  as permissive
  for delete
  to public
using (true);



  create policy "allow insert rant views"
  on "public"."rant_views"
  as permissive
  for insert
  to public
with check (true);



  create policy "allow update rant views"
  on "public"."rant_views"
  as permissive
  for update
  to public
using (true);



  create policy "allow_public_read_views"
  on "public"."rant_views"
  as permissive
  for select
  to public
using (true);



  create policy "Allow delete logs"
  on "public"."view_logs"
  as permissive
  for delete
  to public
using (true);



  create policy "allow insert view logs"
  on "public"."view_logs"
  as permissive
  for insert
  to public
with check (true);



  create policy "allow read view logs"
  on "public"."view_logs"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER article_like_delete AFTER DELETE ON public.article_likes FOR EACH ROW EXECUTE FUNCTION public.decrement_like_count();

CREATE TRIGGER article_like_insert AFTER INSERT ON public.article_likes FOR EACH ROW EXECUTE FUNCTION public.increment_like_count();

CREATE TRIGGER trig_hug_count AFTER INSERT ON public.article_likes FOR EACH ROW EXECUTE FUNCTION public.increment_hug_count();


